### ISSUE TITLE
collections and bundle types

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal_elasticsearch#184]
User is currently asked to select a bundle type when creating a collection.  It is choose one only.

![screen shot 2018-03-19 at 10 42 18 am](https://user-images.githubusercontent.com/7063154/37602200-430eb874-2b62-11e8-94c1-b10263bde8ca.png)

1) Collections now supports multiple bundle types per collection.

2) The *search* interface only lets you filter a single bundle type per search.

I think the correct way to do this is to a) do away with the first question, autodetect what bundles are in the search, and b) make the "filter by bundle" sidebar multiselect.

**Comment by almasaeed2010** [comment]
One major issue that we'll need to think about before implementing this:

What happens when the user didn't select a category from the sidebar?
- We'd either get all available fields in the entire site and represent it to the user to pick from (way too many fields for it to be a useful approach),
- Or detect what bundle types are present in the current search results, which means looping through the results (a max possibility of 1m entities), and get the fields associated with each bundle type.
- We could also display the categories to be picked from only if the user didn't select a category, which may create an inconsistent user experience but is the best solution from a performance point of view.

**Comment by bradfordcondon** [comment]
>What happens when the user didn't select a category from the sidebar?
How about the text displays as "please select one or more category to create a bundle"

**Comment by almasaeed2010** [comment]
Wouldn't that be the same as selecting it in the modal but instead selecting before opening the modal?

**Comment by bradfordcondon** [comment]
if i recall the modal displays ALL bundles not just bundles found in your search?

Plus that way its "more consistent user experience"

Finally I think it will be more clear whats happening because your results get filtered down by bundle type at the search step, versus you dont see the consequences of your choice at the modal step.

**Comment by almasaeed2010** [comment]
The modal now auto selects what you filtered down to.

Thanks!

**Comment by bradfordcondon** [comment]
yay!  this is a big quality of life improvement, thanks abdullah!
