### ISSUE TITLE
TripalEntity indexing slow on large sites

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal_elasticsearch#234]
I've been indexing my Tripal Content for 13 days already and there is another 40 estimated days to go... My cron is setup to run every 15 minutes and we're still noticing significant slow down with this setting. Any ideas for where I should look to speed this process up? I'm really excited to get the site-wide search working on KnowPulse!

<img width="1337" alt="screen shot 2019-01-30 at 9 27 08 am" src="https://user-images.githubusercontent.com/1566301/51993286-2231b500-2474-11e9-8a93-830dd6005e41.png">

**Comment by almasaeed2010** [comment]
Hello @laceysanderson,

I understand your frustration with the slow indexing process 😞It has been a major point of concern for all of us. Indexing entities, unfortunately, has always been slow even after the recent round of updates. To index each entity, we have to load all of its attached fields and most uncached entities take `7` seconds on average to load. In sites that have even more fields, it'll probably be even slower. With that assumption, your site would need `178.54` days to index if it was running constantly (without the 15 minutes cron delay). If we account for the 15 minute delay, the number would go up to `2,678.1` days. 

However, with our bulk loading and bulk indexing technique paired with initial partial loading of entities (round 1), this got reduced significantly to `53` days with the `15` minutes delay (if we allow it to run once every minute, it'd be even faster). 

In addition, I spent some time benchmarking the amount of resources each part of the process needs. As it turns out, the most resource intensive operation is the loading of entities themselves rather than the indexing process that ES handles. I suspect this is due to the intensive number of database and disk operations that entities need to perform to build the page. However, if your ES server is consuming more resources than necessary, we can take a look at the settings to limit the amount of resources the Java virtual machine is allowed to utilize ([this guide could be a good start](https://github.com/tripal/tripal_elasticsearch/blob/master/docs/system-resources.md))

The good news is, Tripal 3 entities allow us to manage what fields to load and index, which has increased the performance by a big factor when compared to Tripal 2 (more than 100 days faster in our case). And just for comparison, our site takes 1 week to index using tripal_elasticsearch whereas using the default Drupal indexing it takes 3+ years 😆 

I'd be more than happy to look at your settings with you to figure out if there is something we can do to control resources 🙂 

Thanks!

**Comment by laceysanderson** [comment]
Ahhh, interesting! Thanks for the quick reply! I also felt that the entity loading was likely the bottleneck. 

> The good news is, Tripal 3 entities allow us to manage what fields to load and index

So setting more fields to "Do not index" in the tuning stage should speed things up?

**Comment by almasaeed2010** [comment]
There is an option to mark some fields as low priority in the `tuning` step. This would allow the indexer to come back later after and add those fields to the index after all entities have finished indexing. It'll also reduce the amount of memory each indexing job consumes so it's definitely worth messing with the tuning form. 

You'll still need to reduce the number of minutes between cron jobs to really see an improvement though.

**Comment by almasaeed2010** [comment]
If you want to run only elasticsearch queues once per minute rather than all cron jobs, you can add this to your cron tab:

```bash
* * * * * drush cron-run queue_elasticsearch_queue_1 --root=/var/www/html
* * * * * drush cron-run queue_elasticsearch_queue_2 --root=/var/www/html
* * * * * drush cron-run queue_elasticsearch_queue_3 --root=/var/www/html
* * * * * drush cron-run queue_elasticsearch_queue_4 --root=/var/www/html
* * * * * drush cron-run queue_elasticsearch_queue_5 --root=/var/www/html
```

**Comment by bradfordcondon** [comment]
is that last pointer in the readme/docs?  I think all users with bigger than tiny sites will run into these speed tuning issues.

**Comment by almasaeed2010** [comment]
I don't think it is. I'll add it.

Thanks!

**Comment by laceysanderson** [comment]
Awesome, I'll try those tips and report back! Thank you <3

**Comment by almasaeed2010** [comment]
Sounds good @laceysanderson 

@bradfordcondon looks like it's already there

**Comment by almasaeed2010** [comment]
Something I noticed today. The bulk of our site consists of features (mrna, genes, etc). This is how long it takes to go through those without having to load entities (ie, direct db operations):

<img width="1396" alt="screen shot 2019-03-04 at 1 37 44 pm" src="https://user-images.githubusercontent.com/1512664/53754855-24c46780-3e83-11e9-9e13-ee865be4bc92.png">

That's about `1,800,000` features (with annotations, blast hit results, relationships, etc) in 3 hours. This is another indicator that loading entities could be very slow compared to directly crawling chado, which makes sense since entities execute a lot more code (and hooks).

**Comment by laceysanderson** [comment]
So I seem to be at a standstill 😞 My indexing has been at this exact point for the last 3 days:
<img width="1014" alt="Screen Shot 2019-03-25 at 2 42 57 PM" src="https://user-images.githubusercontent.com/1566301/54952804-70ab7f00-4f0c-11e9-84ac-ea0fdd2cac91.png">

On Thursday I was really excited because the high priority bar was almost complete and the low priority bar was moving quickly. However, by Friday the low/high priority bars had disappeared (completed?) leaving me only with the overall bar shown in the screenshot above. The ratio of items in that progress bar has not changed at all over 3 days despite my settings remaining the same. I checked my cron and it is still configured properly 😕 

Any idea what is going on?

**Comment by almasaeed2010** [comment]
There have been incidents of the progress bar missing a few items before. Probably caused by some sort of miscalculation. To really checks if you your indexing have completed, check your queues manager page. If there are no items left that belong to ES, then the indexing is complete.

I’ll look again at this tomorrow to see where things can go wrong.

**Comment by laceysanderson** [comment]
> To really checks if you your indexing have completed, check your queues manager page. If there are no items left that belong to ES, then the indexing is complete.

When I go to `Home » Administration » Configuration » System » Queue manager` there are no items at all.

**Comment by almasaeed2010** [comment]
Ok I spent a bit of time looking at the code that reports progress and it makes perfect sense. I can't find any issues with it. It's odd that it always gets stuck near 99%. Maybe we need to implement this based on how many items are in the queue table rather than how many entities are available in the site. Will have to look at what kind of info the queue table provides.

**Comment by almasaeed2010** [comment]
I added a fix for this that makes ES first check if there are items in the queue before reporting progress. That way, if there is a problem in the calculations, this can self-correct.

The master branch has the latest fix and I'll release a new version soon since the fix has been tested on our live site and main dev without issues.

**Comment by laceysanderson** [comment]
That fixes the progress for me 🎉 However, I still don't have the `Tripal Elasticsearch local entities search form` block. How can I access the search?

**Comment by almasaeed2010** [comment]
There should be 2 blocks:

This should be added to the sidebar:
- `Tripal Elasticsearch website search category`

And this should go to content or header
- `Tripal Elasticsearch website search box`

Both `entities` and `website` indices get searched from those same blocks.

**Comment by almasaeed2010** [comment]
That's how Ming made when the module was first developed so we kept the original design since we didn't want to break people's sites 😅

**Comment by laceysanderson** [comment]
<img width="928" alt="Screen Shot 2019-04-04 at 12 24 31 PM" src="https://user-images.githubusercontent.com/1566301/55579063-a43c9500-56d4-11e9-8fca-71c8a2ce1a11.png">

Oh that's nice! I don't have those blocks either tho 🤔 Is there maybe code to trigger only making them available once the site is indexed?

**Comment by almasaeed2010** [comment]
We’ve had that issue before. And here is the fix: https://github.com/tripal/tripal_elasticsearch/issues/201#issuecomment-415130784

I still don’t think I understand what’s going on there though.

**Comment by laceysanderson** [comment]
Worked 🎉 🎉 🎉  Thank you!

**Comment by almasaeed2010** [comment]
Glad to hear it!
