### ISSUE TITLE
A unique constraint should be added to index_name in the indices table 

### ISSUE THREAD

**Issue by almasaeed2010** [tripal/tripal_elasticsearch#240]
We have multiple instances where a failure causes the name of the index to be duplicated. This could be prevented and caught as an error if we have a unique constraint.

**Comment by mboudet** [comment]
Oh, I was actually going to post about this.

Is there any reason why indices are not alway deleted from the tripal_elasticsearch_indices table?

In the [tripal_elasticsearch_delete_index function](https://github.com/tripal/tripal_elasticsearch/blob/master/includes/tripal_elasticsearch.indices.form.inc#L943), there is 
1) A cleanup of the tripal_elasticsearch table (used for search block)
2) If something was deleted, then cleanup the other two tables.

Meaning, if no search block was created, the indices will not be removed from the indices table.

![image](https://user-images.githubusercontent.com/17642511/53097454-c661c580-3521-11e9-8f6c-8fffc20d49f9.png)

Which leads to duplicates if the indice is re-created.
It should probably be fixed before adding an unique constraint, otherwise it's going to crash.

**Comment by almasaeed2010** [comment]
Let's create an update function that deletes everything except the last record for each duplicate entry then add a unique constraint.

**Comment by almasaeed2010** [comment]
The PR has been merged. Thanks!
