### ISSUE TITLE
No search result while indexing

### ISSUE THREAD

**Issue by admi2u** [tripal/tripal_elasticsearch#266]
Hi,
I have used tripal elasticsearch to create an index of the Tripal Entities. I have noticed that during the indexing step, the elasticsearch engine can not retrieve any search result. Is this normal that the elasticsearch engine will not work until the full index was created? Should I wait until the index step finish (which is quite slow)?
The docker image version of the elasticsearch I am using is 6.7.2

![indexing](https://user-images.githubusercontent.com/36391186/68930043-8554c400-07c8-11ea-8db9-7789a4e0bf73.png)
![search-result](https://user-images.githubusercontent.com/36391186/68930051-8ab20e80-07c8-11ea-8614-a31252524e25.png)

**Comment by almasaeed2010** [comment]
Hello @admi2u 

This is not normal. Results should start showing up immediately. The only reason we've encountered before that causes this was that entities permissions weren't set properly. The `entity type: View Content` permissions in `People > Permissions` have to be available to anonymous users. Only content that's available to anonymous users will be indexed. Otherwise, the indexer will skip the entity.

Could you also check `Reports > Recent log messages` in case there are any error messages?

If you find permissions issues, you can restart the indexer by first clearing the jobs from `Configuration > System > Queue Manager` and deleting any queues that have `elasticsearch` in the name. Then, you can rerun the indeexer to dispatch new jobs. There is no need to worry about the content of the index since the module will automatically detect whether an entity has been previously indexed.

Please let us know if this helps. 

Thanks!

**Comment by admi2u** [comment]
Hello @almasaeed2010 

Thank you for your reply. I have configured the anonymous user access to the entity before the establishment of the `Tripal Entities` index, and there are no error messages report in the `report -> recent log messages.`
Strangely, today when I found the index completion progress of about 50%, there are extra `website indexes` in the index type as shown below, some data results can already be displayed in the search results.
![extra index type](https://user-images.githubusercontent.com/36391186/69019245-b4e31680-09ea-11ea-9259-9d8ca0a1757c.png)
![index progress](https://user-images.githubusercontent.com/36391186/69019298-f5429480-09ea-11ea-9d23-82a8344c0098.png)
![search results](https://user-images.githubusercontent.com/36391186/69019304-f83d8500-09ea-11ea-8365-d39be2a2487f.png)

So, I don't know exactly what caused this. May be because of the docker image version of Elasticsearch ?

**Comment by almasaeed2010** [comment]
I am not sure what could be the issue. Do you see any content types (categories) missing from the sidebar?

**Comment by admi2u** [comment]
The categories from the sidebar are consistent with the site configuration. So there are no missing categories found. 
Although the use of  `tripal-elasticsearch` this time is not the same as the previous, but for now, the search results are correct.

**Comment by almasaeed2010** [comment]
I am not what caused the delay for the results to show up, but I think this has been resolved. Thanks for reporting the issue. If you do encounter any other issues, please don't hesitate to report them to us. Thanks!
